endpoint funcionando y conexion exitosa
3ettilina/qrlink-back pull request #1
Opened 2022-10-23 18:37 UTC by Franko94

2022-10-24 00:22 UTC, 3ettilina requested changes
Impeca el laburo! Dejé unos comentarios de mejoras antes de mergear.

2022-10-24 00:22 UTC, 3ettilina commented on src/main/java/com/ucu/taisback/controller/BackendController.java
> +    @GetMapping("/getProduct")
Creo que sería mejor cambiar este endpoint a algo como `/getProductResource`. Sería ideal agregar un TODO para después, no es necesario hacer el cambio ahora.

2022-10-24 00:22 UTC, 3ettilina commented on src/main/java/com/ucu/taisback/controller/BackendController.java
> +     RedirectView redirectView =  new RedirectView(firebaseService.getProduct(productId).getResource_url());
Antes de hacer getResource_url() debemos asegurarnos que el producto existe en la base de datos. 
Si no existe, retornamos `HTTP 404` con body 
```
{
    "error": `El producto con GTIN: ${productGtin} 
    no existe en el sistema.`,
}
```
Cualquier otra excepción hay que catchearla y retornar un HTTP 500 con body 
```
{
    "error": `Ha ocurrido un error inesperado, 
    por favor intenta de nuevo.`,
}
```
Esto debe ser cambiado para poder aprobar el PR.

2022-10-24 00:22 UTC, 3ettilina commented on src/main/java/com/ucu/taisback/service/FirebaseService.java
> +  }
Agregar `try catch` a todo el bloque y retornar la excepción hacia abajo para evitar que la app falle inesperadamente.

2022-10-24 00:22 UTC, 3ettilina commented on src/main/resources/application.properties
> +
Este archivo se usa?

2022-10-25 16:24 UTC, Franko94 commented on src/main/java/com/ucu/taisback/service/FirebaseService.java
> +  }
No es necesario, esta el throws en la firma del metodo

2022-10-25 16:24 UTC, Franko94 commented on src/main/resources/application.properties
> +
si

2022-10-25 22:33 UTC, 3ettilina approved these changes
Aprobado!

2022-10-27 11:43 UTC, 3ettilina approved these changes

2022-10-27 11:56 UTC, merged