nuevo endpoint y problemas de branch solucionados
3ettilina/qrlink-back pull request #10
Opened 2022-10-31 19:12 UTC by Franko94

2022-11-01 02:01 UTC, 3ettilina requested changes
Mejorar el manejo de excepciones. Devolver 404 si no existe el producto y 500 si hubo cualquier otro error.

2022-11-01 02:01 UTC, 3ettilina commented on src/main/java/com/ucu/taisback/controller/BackendController.java
> +    return firebaseService.getProduct(gtin);
Estas Excepciones se catchean o qué pasa si te mando un gtin que no existe?

2022-11-01 02:01 UTC, 3ettilina commented on src/main/java/com/ucu/taisback/TaisBackApplication.java
> +		return new CorsFilter( urlBasedCorsConfigurationSource);
Por alguna razón esto me dio un problema el otro día. Te dejo la nota acá por las dudas, pero lo voy a probar.

2022-11-01 13:35 UTC, Franko94 commented on src/main/java/com/ucu/taisback/controller/BackendController.java
> +    return firebaseService.getProduct(gtin);
ya esta contemplado, lo podes probar mandando un codigo que no existe

2022-11-02 00:45 UTC, 3ettilina approved these changes
Aprobado y testeado!

2022-11-02 00:56 UTC, merged